language: cpp
compiler: gcc
sudo: required
dist: xenial
notifications:
  email: false

before_script:
  # install cmake
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  # build gtest
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ../
  - make
  - ./tests/cprogen_core_tests
  - cd ../tests
  - python3 -m unittest

addons:
  apt:
    packages:
      - libgtest-dev
